Frosty04
chingu-voyages/v49-tier2-team-16 pull request #45
Opened 2024-05-28 20:12 UTC by frosty8104

2024-05-28 20:41 UTC, mnichols08 commented on src/components/Display.jsx
> +function Display() {
Maybe we should give this a more descriptive name

2024-05-28 20:43 UTC, mnichols08 approved these changes
I like that you introduced a new component for displaying the objects. I understand that you still need access to the design file in order to implement the design more - and also you require a dataset from whoever is supplying this component with data. I made a suggestion that maybe we should be more specific about the name because it is likely we will want to display other things as well.

2024-05-28 22:34 UTC, Valeriusdev requested changes
Please exclude the changes to package-lock.json and package.json from the PR. Also, ensure that the branch deploys successfully before merging it into the development branch.

2024-05-29 10:41 UTC, mnichols08 commented
This is failing a deploy again after the most recent code push.

We might have to delete this particular package-lock.json file to fix.

```
10:55:18 PM: $ npm run build
10:55:18 PM: > v49-tier2-team-16@0.0.0 build
10:55:18 PM: > vite build
10:55:18 PM: /opt/build/repo/node_modules/vite/node_modules/rollup/dist/native.js:59
10:55:18 PM: 		throw new Error(
10:55:18 PM: 		      ^
10:55:18 PM: Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
```

2024-05-29 12:53 UTC, Valeriusdev requested changes
Please exclude the changes to package-lock.json and package.json from the PR. Also, ensure that the branch deploys successfully before merging it into the development branch.

2024-05-30 21:36 UTC, KseniiaRiabova commented
PR has been closed due to incorrect implementation

2024-05-30 21:56 UTC, closed without merging