Text section
chingu-voyages/v49-tier2-team-16 pull request #57
Opened 2024-06-04 22:05 UTC by frosty8104

2024-06-04 22:12 UTC, mnichols08 commented on src/components/DisplayColours.jsx
> +    <TextSection />
This component is not getting any properties passed in, causing the app to crash when it renders.

2024-06-04 22:14 UTC, mnichols08 commented on src/components/TextSection.jsx
> +function TextSection() {
this function should receive a color as an argument, or somehow learn about the color we are referring to on lines 13 + 14

2024-06-04 22:14 UTC, mnichols08 commented on src/components/DisplayColours.jsx
>          <div key={color.hex}>
This component may below inside of this map, passing in the `color` that the map is on at the moment.

2024-06-04 22:15 UTC, mnichols08 requested changes
Currently this crashes the app due to a color not being passed into `TextSection`

2024-06-05 14:20 UTC, mnichols08 commented
There are still changes that may come with this, but we are very close to matching the design file in this Branch.

This is a combination PR of the code that @mnichols08 is working on for the Image Generator and @frosty8104 is working on for the Left Portion showing the palette generated by GroqAPI

The image I have chose for loading can be changed and maybe we could animate the compass or something. Just didnt't want a static "loading..." message.

2024-06-05 18:44 UTC, mnichols08 commented on src/components/DisplayColours.jsx
I mentioned this to you in chat but it may make sense to convert the name of this component from DisplayColours to something more descriptive like ResultsSection or etc.

2024-06-05 18:45 UTC, mnichols08 commented on src/components/TextSection.jsx
And here maybe we could change the TextSection component name to DisplayColours as its more descriptive of it now

2024-06-05 18:45 UTC, mnichols08 approved these changes
Looking great!

2024-06-05 19:39 UTC, mnichols08 commented on src/App.jsx
> +import DisplayColours from "./components/DisplayColours";
We got a little confused on the renaming.

Let's call this one ResultsSection

2024-06-05 19:39 UTC, mnichols08 commented on src/App.jsx
> +          <DisplayColours colors={colors} prompt={prompt} />
`<ResultsSection>` here too

2024-06-05 19:41 UTC, mnichols08 approved these changes
Still approve the merge but added additional feedback

2024-06-05 19:41 UTC, mnichols08 commented on src/components/ResultsSection.jsx
And this file maybe se call DisplayColours as thats what are doing within this component

2024-06-05 19:41 UTC, mnichols08 commented on src/components/DisplayColours.jsx
> +function DisplayColours({ colors, prompt }) {
I propose renaming this to ResultsSection

2024-06-06 01:18 UTC, mnichols08 commented
![image](https://github.com/chingu-voyages/v49-tier2-team-16/assets/33106391/67ec2b48-4301-4aa7-a785-63e8eb9c14b1)
^^ Loading Screen
![image](https://github.com/chingu-voyages/v49-tier2-team-16/assets/33106391/3255fe5f-4d61-442e-92d5-8ade92f9ebc6)
^^ After loaded...
![image](https://github.com/chingu-voyages/v49-tier2-team-16/assets/33106391/c8fb2606-05cd-42dc-b65b-1d6f9eb9261a)
^^ Figma Design File


This feature is nearly complete. Please let us know if you see anything to change

2024-06-06 04:17 UTC, mnichols08 commented
![image](https://github.com/chingu-voyages/v49-tier2-team-16/assets/33106391/c1eb4179-26ec-444a-854b-e4a181fbfb2e)
![image](https://github.com/chingu-voyages/v49-tier2-team-16/assets/33106391/bd7bb1a6-bb2d-448e-900e-bf2864e23810)

2024-06-06 04:18 UTC, mnichols08 commented
Looks like still need to move the Title above the left column and maybe tweak the border radius on the image generated but almost the same as our design file =)

2024-06-06 04:45 UTC, mnichols08 commented
![image](https://github.com/chingu-voyages/v49-tier2-team-16/assets/33106391/2d7469f8-e73d-4c8b-bebc-14b5dbce95be)

2024-06-06 14:28 UTC, mnichols08 reviewed
I should not be on the list of reviewers as @frosty8104 and I both have contributions within this PR. But I want to say this is probably close to 98.9% complete. 

It should be safe to merge but there are a lot of commits. I apologize for this. Just habitual for me to commit often

We could consider squashing them but I would argue against it.
I am willing to compromise but here is my logic:
1. Detailed History: Each atomic commit represents a single change or small set of related changes, making it easier to understand the history of the codebase.
2. Rollback: If a bug is introduced, it’s easier to revert a single commit without losing other unrelated changes.
3. Frequent Testing: Each atomic commit can trigger a CI build, ensuring that changes are tested frequently and issues are caught early.

Reasons to consider squashing that I am a fan of are:
1. Simplified Log: Squashing commits results in a cleaner, more readable commit history, making it easier to understand the overall evolution of the project without the noise of minor commits.
2. Conflict Resolution: Squashing can simplify conflict resolution, as there are fewer commits to manage during merges.
3. Logical Grouping: Changes that belong together are grouped together, which can make the history easier to follow at a higher level.

A suggestion for reviewing this PR is to NOT look at each and every individual commit, but to instead look under the Files Changed tab and go through each file line by line adding comments and questions / concerns as you see them. Check the file off as viewed and move on the next one.

2024-06-07 08:02 UTC, NadiiaLashtun approved these changes
You have done a big job! It's amazing!

2024-06-07 08:02 UTC, NadiiaLashtun commented on src/components/MainSection.jsx
> +              <h1 className="font-caption items-center text-center text-6xl md:text-8xl lg:text-[110px] text-brand-light-green">
Why did you add these styles here? These are duplicates of the styles added for the div above that includes this element.

2024-06-07 08:02 UTC, NadiiaLashtun commented on src/index.css
> +.results-title {
If you want to reuse this styles for different elements it should be better to use '@apply' here. In other case it should be better to add it in jsx file 
![image](https://github.com/chingu-voyages/v49-tier2-team-16/assets/123567596/f049e413-1120-4909-9a5f-5e8010636171)

2024-06-07 08:02 UTC, NadiiaLashtun commented on src/index.css
> +.circle-color-box {
The same according this

2024-06-07 12:55 UTC, mnichols08 commented on src/components/MainSection.jsx
> +              <h1 className="font-caption items-center text-center text-6xl md:text-8xl lg:text-[110px] text-brand-light-green">
Great catch and even better question 🫣

I am not sure what we were thinking here to be honest. I think maybe a mistake as we probably didn't need to change anything in this file for our changes.

2024-06-07 12:56 UTC, mnichols08 commented on src/index.css
> +.results-title {
This is great advice thanks for the suggestion

2024-06-07 22:53 UTC, KseniiaRiabova approved these changes

2024-06-07 22:53 UTC, merged